apiVersion: v1
kind: Service
metadata:
  name: estetik-app-frontend
  namespace: estetik-dev
  labels:
    app: estetik-app-frontend
spec:
  type: ClusterIP
  selector:
    app: estetik-app-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
